# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Enonic < Formula
  desc "Command-line interface for Enonic XP"
  homepage "https://enonic.com/"
  version "3.1.2"

  on_macos do
    on_intel do
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/3.1.2/enonic_3.1.2_Darwin_64-bit.tar.gz"
      sha256 "bbaf18bed192c67b2a17fa2a60126a5ad2fbcc6947d0982612d68e3a963e191d"

      def install
        bin.install "enonic"
      end
    end
    on_arm do
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/3.1.2/enonic_3.1.2_Darwin_arm64.tar.gz"
      sha256 "f3673ea911597c1c6f4ba2baa89340e6f460c67d1a01795e0e189e8253905218"

      def install
        bin.install "enonic"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://repo.enonic.com/public/com/enonic/cli/enonic/3.1.2/enonic_3.1.2_Linux_64-bit.tar.gz"
        sha256 "095a0b18b2c274cc5c97f70ceef69963df18dbe2ee607ab27504fb068844aa0c"

        def install
          bin.install "enonic"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://repo.enonic.com/public/com/enonic/cli/enonic/3.1.2/enonic_3.1.2_Linux_arm_v6.tar.gz"
        sha256 "36cb34d4b4caa0b926a3051d3874d6438b48d144db3062d4a6be207b587ebb7d"

        def install
          bin.install "enonic"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://repo.enonic.com/public/com/enonic/cli/enonic/3.1.2/enonic_3.1.2_Linux_arm64.tar.gz"
        sha256 "a0bf97b81d177dbb709aa8bacb8ec8297a4003bd0c05aea66187818644d9d253"

        def install
          bin.install "enonic"
        end
      end
    end
  end
end
