# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Enonic < Formula
  desc "Command-line interface for Enonic XP"
  homepage "https://enonic.com/"
  version "3.1.1"

  on_macos do
    on_intel do
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/3.1.1/enonic_3.1.1_Darwin_64-bit.tar.gz"
      sha256 "4e39f633f21d46b612d137c1f84adfbb3bcc29a6a429abe683ffed2c9fa80b16"

      def install
        bin.install "enonic"
      end
    end
    on_arm do
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/3.1.1/enonic_3.1.1_Darwin_arm64.tar.gz"
      sha256 "8490208291b52dbfd31e6b3ed72eb2e8011ecc7b4b6dfc1cb7cb8717dd863f38"

      def install
        bin.install "enonic"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://repo.enonic.com/public/com/enonic/cli/enonic/3.1.1/enonic_3.1.1_Linux_64-bit.tar.gz"
        sha256 "567f1bcc8429514c8b7658e401a16d3bda414fad81db3a946ea968e88e9448d0"

        def install
          bin.install "enonic"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://repo.enonic.com/public/com/enonic/cli/enonic/3.1.1/enonic_3.1.1_Linux_arm_v6.tar.gz"
        sha256 "e2d10b27c4a139346403356de9f1d0c19dbcc6cb2792d8741294d836af60fc3f"

        def install
          bin.install "enonic"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://repo.enonic.com/public/com/enonic/cli/enonic/3.1.1/enonic_3.1.1_Linux_arm64.tar.gz"
        sha256 "9a0696f367009c7badd9bf5fe51ea4a8447465431daf8e180c3711bcdc4eaba6"

        def install
          bin.install "enonic"
        end
      end
    end
  end
end
