# This file was generated by GoReleaser. DO NOT EDIT.
cask "enonic" do
  version "4.0.0-B4"

  on_macos do
    on_intel do
      sha256 "d040df86cc1dc5b2ff1db9178eb58f9f52fffa53facce65402800d5ff9963b7d"
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/#{version}/enonic_#{version}_Darwin_64-bit.tar.gz",
        verified: "https://repo.enonic.com"
    end
    on_arm do
      sha256 "68075f89007eb703f1acd76c1ed50f9ed9af335aa472903832d87ff6e33c28a3"
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/#{version}/enonic_#{version}_Darwin_arm64.tar.gz",
        verified: "https://repo.enonic.com"
    end
  end

  on_linux do
    on_intel do
      sha256 "3a456a1f483233e22ca295b4a613f21dbc211f9a2af80576bea4ecc2d0533957"
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/#{version}/enonic_#{version}_Linux_64-bit.tar.gz",
        verified: "https://repo.enonic.com"
    end
    on_arm do
      sha256 "e63c6e066c72c420038660b01f9fedf7116327724d00cfe8a7a0c6036709f2aa"
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/#{version}/enonic_#{version}_Linux_arm64.tar.gz",
        verified: "https://repo.enonic.com"
    end
  end

  name "enonic"
  desc "Command-line interface for Enonic XP"
  homepage "https://enonic.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "enonic"

  # No zap stanza required

end
