# This file was generated by GoReleaser. DO NOT EDIT.
cask "enonic" do
  version "4.0.0-B2"

  on_macos do
    on_intel do
      sha256 "ffc5e3c7483e9596f2953b98059e09869271e894ee5b129f09ff9c28bc9c1ae7"
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/#{version}/enonic_#{version}_Darwin_64-bit.tar.gz",
        verified: "https://repo.enonic.com"
    end
    on_arm do
      sha256 "8ec82ebaf50b62967ad39e4227f023fd4926afebd0b45f80c11328c5a1067f6d"
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/#{version}/enonic_#{version}_Darwin_arm64.tar.gz",
        verified: "https://repo.enonic.com"
    end
  end

  on_linux do
    on_intel do
      sha256 "cb86f76f3fb316dba7cfc03bd7404bb7519f4accc8d1a6283a09db4b8fbbe853"
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/#{version}/enonic_#{version}_Linux_64-bit.tar.gz",
        verified: "https://repo.enonic.com"
    end
    on_arm do
      sha256 "a928d674342df2b622c10d4181ea1d5ccd82bcaaaf161c57c0d6f2b7e1144e25"
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/#{version}/enonic_#{version}_Linux_arm64.tar.gz",
        verified: "https://repo.enonic.com"
    end
  end

  name "enonic"
  desc "Command-line interface for Enonic XP"
  homepage "https://enonic.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "enonic"

  # No zap stanza required

end
