# This file was generated by GoReleaser. DO NOT EDIT.
cask "enonic" do
  name "enonic"
  desc "Command-line interface for Enonic XP"
  homepage "https://enonic.com/"
  version "3.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "enonic"

  on_macos do
    on_intel do
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/#{version}/enonic_#{version}_Darwin_64-bit.tar.gz",
        verified: "https://repo.enonic.com"
      sha256 "1c95dbcb54a87c0cbdc64b30e0d355adb0b69afea20026600eec792088bce15a"
    end
    on_arm do
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/#{version}/enonic_#{version}_Darwin_arm64.tar.gz",
        verified: "https://repo.enonic.com"
      sha256 "f55d65f8449fd85bb5a1e521fceefa1b974bfc754ab7567c2c01c5df7a4efbbd"
    end
  end

  on_linux do
    on_intel do
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/#{version}/enonic_#{version}_Linux_64-bit.tar.gz",
        verified: "https://repo.enonic.com"
      sha256 "86cd1aab6b1735a6ece8ca159c2114846b1dca79fb805ce446c26d682754e4b1"
    end
    on_arm do
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/#{version}/enonic_#{version}_Linux_arm64.tar.gz",
        verified: "https://repo.enonic.com"
      sha256 "736eec1517c536e71c66194e347937a038b41056b21a79ec75abe56cc1bd22ae"
    end
  end

  # No zap stanza required
end
