# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Enonic < Formula
  desc "Command-line interface for Enonic XP"
  homepage "https://enonic.com/"
  version "2.4.0-RC3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/2.4.0-RC3/enonic_2.4.0-RC3_Darwin_64-bit.tar.gz"
      sha256 "98649aebd19652f420053609d06a33e232c9ab3e729bbc1b9464a4894ff22df2"

      def install
        bin.install "enonic"
      end
    end
    if Hardware::CPU.arm?
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/2.4.0-RC3/enonic_2.4.0-RC3_Darwin_arm64.tar.gz"
      sha256 "fc7f7a26050347ec8b09e2f45d034f3e9559d5c06b723b3c1a22a1beff78eb77"

      def install
        bin.install "enonic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/2.4.0-RC3/enonic_2.4.0-RC3_Linux_64-bit.tar.gz"
      sha256 "bde4582ab3453592fc417120c2737dc366cea14172098995b1f9177950648cfc"

      def install
        bin.install "enonic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/2.4.0-RC3/enonic_2.4.0-RC3_Linux_arm64.tar.gz"
      sha256 "83e467d4478d99828821e3d3b2205c5432974fe831d67b50232cc7ee92253e76"

      def install
        bin.install "enonic"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/2.4.0-RC3/enonic_2.4.0-RC3_Linux_arm_v6.tar.gz"
      sha256 "3de57fc436110c6aac6f764d954565f87d37ad25b744c85ab72c4a051516fa9e"

      def install
        bin.install "enonic"
      end
    end
  end
end
