# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Enonic < Formula
  desc "Command-line interface for Enonic XP"
  homepage "https://enonic.com/"
  version "2.8.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/2.8.2/enonic_2.8.2_Darwin_64-bit.tar.gz"
      sha256 "efd3bd9d717ceba723e24e7b30422290c5ac975614ab63195b765267374f5fa5"

      def install
        bin.install "enonic"
      end
    end
    if Hardware::CPU.arm?
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/2.8.2/enonic_2.8.2_Darwin_arm64.tar.gz"
      sha256 "3ab916ea2c041f229f0f2c15d8a729e1a32da3aa88660e1833f0ccf7af6579e8"

      def install
        bin.install "enonic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/2.8.2/enonic_2.8.2_Linux_arm64.tar.gz"
      sha256 "3ecb4ba9721c83dd2146c00149644b5955262e291e0ed62d2829d3316869bed8"

      def install
        bin.install "enonic"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/2.8.2/enonic_2.8.2_Linux_arm_v6.tar.gz"
      sha256 "4045c830562d978f98b1241f26e0fea2ae2da82bc9c5ee52fe97013f859c0fc7"

      def install
        bin.install "enonic"
      end
    end
    if Hardware::CPU.intel?
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/2.8.2/enonic_2.8.2_Linux_64-bit.tar.gz"
      sha256 "80754d46d5862c0e8dc3170a7e6a6c873811fb6ac4538ebab4dc8afa3b3a6aee"

      def install
        bin.install "enonic"
      end
    end
  end
end
