# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Enonic < Formula
  desc "Command-line interface for Enonic XP"
  homepage "https://enonic.com/"
  version "2.8.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/2.8.1/enonic_2.8.1_Darwin_64-bit.tar.gz"
      sha256 "0fa1b8c28dd1107f9cdcb6d3bb6190a0942ed44dc78f986592a97fc90d3ffed6"

      def install
        bin.install "enonic"
      end
    end
    if Hardware::CPU.arm?
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/2.8.1/enonic_2.8.1_Darwin_arm64.tar.gz"
      sha256 "dd441be5e662047ea36be8dedaea9f198cc34daded37325d5d1a2535c0da530c"

      def install
        bin.install "enonic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/2.8.1/enonic_2.8.1_Linux_arm_v6.tar.gz"
      sha256 "268fcb610f982125cf423575b994db48faebc7a2430078926844b5df3460e83f"

      def install
        bin.install "enonic"
      end
    end
    if Hardware::CPU.intel?
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/2.8.1/enonic_2.8.1_Linux_64-bit.tar.gz"
      sha256 "75c386c4b38d137b4825442a00a91e2097e954902569541e7c9b2a8f2f3e7578"

      def install
        bin.install "enonic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://repo.enonic.com/public/com/enonic/cli/enonic/2.8.1/enonic_2.8.1_Linux_arm64.tar.gz"
      sha256 "94c6125447867fa8f5919455f09090a64f20a0a059b708f2f59f758074a0b62a"

      def install
        bin.install "enonic"
      end
    end
  end
end
